services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: matanx/wog:latest
    container_name: WorldOfGame
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main_score.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
  # Add other services if needed, e.g., a database service

  # Optional: Define a network if needed
networks:
  default:
    driver: bridge
