services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: matanx/wog:latest
    container_name: WorldOfGame
    ports:
      - "8777:5000"
    environment:
      FLASK_APP: main_score.py
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0
  

  
networks:
  default:
    driver: bridge
